version: '3.8'

services:
  crypto-investment-quarkus:
    image: crypto-investment-quarkus
    container_name: crypto-investment-quarkus
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: crypto
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"